### ISSUE TITLE
Use kubernetes kyverno: v1 19.8 the image built as the basic image is always in the waiting state during operation

### ISSUE THREAD

**Issue by Stevent-fei** [alibaba/sealer#1223]
![image](https://user-images.githubusercontent.com/65949637/157210799-6af3e5a3-8647-4cb7-acaa-2367ad6564b2.png)
![image](https://user-images.githubusercontent.com/65949637/157211887-2829623f-7291-4f96-8805-c697d008a3d9.png)

The basic image used is kubernetes kyverno: v1 19.8 the image built in 19.8 can't get up in the pod and is always in the waiting state

**Comment by Stevent-fei** [comment]
![image](https://user-images.githubusercontent.com/65949637/157213696-e455d3bc-c1fa-4e77-8629-4171df255627.png)
Running to this step will get stuck

**Comment by bxy4543** [comment]
You're not up because the Calico network isn't up；

kyverno redirect-registry policy is invalied:

Kubefile:
![image](https://user-images.githubusercontent.com/69408038/157848174-4dfa10b9-7372-4665-a337-0b54115529d9.png)
raw docker version:
![image](https://user-images.githubusercontent.com/69408038/157848288-1dd2800b-45ce-4825-a75e-b643f7bb5a93.png)

redirect-registry policy is invalied:
![image](https://user-images.githubusercontent.com/69408038/157848392-0d716f43-c8b6-44bb-b364-e66c0cd5f2ce.png)
![image](https://user-images.githubusercontent.com/69408038/157848428-84703707-fa6f-4914-825c-0bd981a0789f.png)

**Comment by Stevent-fei** [comment]
We have replaced the network plug-in calico - > hybridnet. It seems that this plug-in will also affect kyverno
